#############
# RESOURCES #
#############
resources:

- name: gpdb_src
  type: git
  source:
    branch: 4.3_STABLE
    private_key: {{gpdb-git-key}}
    uri: git@github.com:greenplum-db/gpdb4.git 
    ignore_paths:
      - README.md
      - LICENSE
      - COPYRIGHT
      - .gitignore

- name: orca_github_release
  type: github-release
  source:
    user: greenplum-db 
    repository: gporca
    access_token: {{gporcabot_access_token}}

- name: xerces_patch
  type: git
  source:
    branch: 2X
    paths:
    - patches/xerces-c-gpdb.patch
    - concourse/xerces-c
    - concourse/package_tarball.bash
    uri: https://github.com/greenplum-db/gporca

- name: orca_src
  type: git
  source:
    branch: 2X
    uri: https://github.com/greenplum-db/gporca

- name: bin_xerces_centos5
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_xerces_centos5.tar.gz

- name: bin_orca_centos5_debug
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_orca_centos5_debug.tar.gz

- name: bin_orca_centos5_release
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_orca_centos5_release.tar.gz

- name: centos-gpdb-dev-5
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb4-centos5-build-test
    tag: latest

- name: centos-gpdb-dev-6
  type: registry-image
  source:
    repository: gcr.io/data-orca/centos-gpdb-dev
    tag: "6"

- name: ccache_gpdb_centos5
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{gpdb-artifacts-bucket}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: ccache_gpdb_centos5/ccache_gpdb.tar.gz

- name: bin_gpdb_centos
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: sync_tools_gpdb_centos
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{s3_secret_access_key}}
    versioned_file: sync_tools_gpdb_centos/sync_tools_gpdb.tar.gz

########
# JOBS #
########
jobs:
- name: orca_publish_tag
  max_in_flight: 1
  plan:
  - aggregate:
    - get: orca_src
      passed:
      - orca_centos5_release
      - orca_centos5_debug
      trigger: true
    - get: bin_orca_centos5_release
      passed:
      - orca_centos5_release
    - get: bin_orca_centos5_debug
      passed:
      - orca_centos5_debug
  - task: orca_publish_tag
    file: orca_src/concourse/publish_tag.yml
  - task: check_existing_tag
    file: orca_src/concourse/check_existing_tag.yml
  - put: orca_github_release
    params:
      name: orca_github_release_stage/tag.txt
      tag: orca_github_release_stage/tag.txt
      commitish: orca_github_release_stage/commit.txt
      globs:
        - orca_github_release_stage/bin_orca_centos5_release.tar.gz
        - orca_github_release_stage/bin_orca_centos5_debug.tar.gz

- name: xerces_centos5
  max_in_flight: 2
  plan:
  - get: xerces_patch
    trigger: true
  - aggregate:
    - task: build
      file: xerces_patch/concourse/xerces-c/build_xerces_centos5.yml
  - aggregate:
    - task: package_tarball
      file: xerces_patch/concourse/xerces-c/package_tarball_centos5.yml
  - aggregate:
    - put: bin_xerces_centos5
      params:
        from: package_tarball_centos5/bin_xerces_centos5.tar.gz

- name: orca_centos5_release
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_xerces_centos5
    passed:
    - xerces_centos5
  - task: build_and_test_release
    file: orca_src/concourse/build_and_test_centos5_release.yml
  - task: package_tarball_release
    file: orca_src/concourse/package_tarball_centos5_release.yml
  - put: bin_orca_centos5_release
    params:
      from: package_tarball_release/bin_orca_centos5_release.tar.gz

- name: orca_centos5_debug
  max_in_flight: 2
  plan:
  - get: orca_src
    trigger: true
  - get: bin_xerces_centos5
    passed:
    - xerces_centos5
  - task: build_and_test_debug
    file: orca_src/concourse/build_and_test_centos5_debug.yml
  - task: package_tarball_debug
    file: orca_src/concourse/package_tarball_centos5_debug.yml
  - put: bin_orca_centos5_debug
    params:
      from: package_tarball_debug/bin_orca_centos5_debug.tar.gz

- name: compile_gpdb_centos
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
    - get: centos-gpdb-dev-5
    - get: ccache_snapshot
      resource: ccache_gpdb_centos5
    - get: centos-gpdb-dev-6
    - &get_released_orca
      get: bin_orca
      resource: orca_github_release
      params:
        globs:
          - bin_orca_centos5_release.tar.gz
      passed:
      - orca_publish_tag
      trigger: true
    - get: bin_xerces
      resource: bin_xerces_centos5
      passed:
      - xerces_centos5
  - task: get_ivy_dependencies
    file: gpdb_src/ci/concourse/get_ivy_dependencies.yml
    image: centos-gpdb-dev-6
    params:
      IVYREPO_HOST: {{ivyrepo_host}}
      IVYREPO_REALM: {{ivyrepo_realm}}
      IVYREPO_USER: {{ivyrepo_user}}
      IVYREPO_PASSWD: {{ivyrepo_passwd}}
      TASK_OS: centos
      TASK_OS_VERSION: 6
      TARGET_OS: centos
      TARGET_OS_VERSION: 5
  - task: compile_gpdb
    file: gpdb_src/ci/concourse/compile_gpdb.yml
    image: centos-gpdb-dev-5
    params:
      TARGET_OS: centos
      TARGET_OS_VERSION: 5
      BLD_TARGETS:
  - aggregate:
    - put: bin_gpdb_centos
      params:
        file: gpdb_artifacts/bin_gpdb.tar.gz
    - put: sync_tools_gpdb_centos
      params:
        file: gpdb_artifacts/sync_tools_gpdb.tar.gz
    - put: ccache_gpdb_centos5
      params:
        file: gpdb_artifacts/ccache_gpdb.tar.gz

- name: icg_orca_centos
  plan:
  - aggregate:
    - get: gpdb_src
      passed:
      - compile_gpdb_centos
    - get: sync_tools_gpdb
      passed:
      - compile_gpdb_centos
      resource: sync_tools_gpdb_centos
    - get: bin_gpdb
      passed:
      - compile_gpdb_centos
      trigger: true
      resource: bin_gpdb_centos
    - get: centos-gpdb-dev-5
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      BLDWRAP_POSTGRES_CONF_ADDONS: fsync=off optimizer=on
      MAKE_TEST_COMMAND: installcheck-good
      TEST_OS: centos
    image: centos-gpdb-dev-5

- name: icg_planner_centos
  plan:
  - aggregate:
    - get: gpdb_src
      passed:
      - compile_gpdb_centos
    - get: sync_tools_gpdb
      passed:
      - compile_gpdb_centos
      resource: sync_tools_gpdb_centos
    - get: bin_gpdb
      passed:
      - compile_gpdb_centos
      trigger: true
      resource: bin_gpdb_centos
    - get: centos-gpdb-dev-5
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      BLDWRAP_POSTGRES_CONF_ADDONS: fsync=off
      MAKE_TEST_COMMAND: installcheck-good
      TEST_OS: centos
    image: centos-gpdb-dev-5

- name: icb_orca_centos
  plan:
  - aggregate:
    - get: gpdb_src
      passed:
      - compile_gpdb_centos
    - get: sync_tools_gpdb
      passed:
      - compile_gpdb_centos
      resource: sync_tools_gpdb_centos
    - get: bin_gpdb
      passed:
      - compile_gpdb_centos
      trigger: true
      resource: bin_gpdb_centos
    - get: centos-gpdb-dev-5
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      BLDWRAP_POSTGRES_CONF_ADDONS: fsync=off optimizer=on
      MAKE_TEST_COMMAND: installcheck-bugbuster
      TEST_OS: centos
    image: centos-gpdb-dev-5

- name: icb_planner_centos
  plan:
  - aggregate:
    - get: gpdb_src
      passed:
      - compile_gpdb_centos
    - get: sync_tools_gpdb
      passed:
      - compile_gpdb_centos
      resource: sync_tools_gpdb_centos
    - get: bin_gpdb
      passed:
      - compile_gpdb_centos
      trigger: true
      resource: bin_gpdb_centos
    - get: centos-gpdb-dev-5
  - task: ic_gpdb
    file: gpdb_src/ci/concourse/ic_gpdb.yml
    params:
      BLDWRAP_POSTGRES_CONF_ADDONS: fsync=off
      MAKE_TEST_COMMAND: installcheck-bugbuster
      TEST_OS: centos
    image: centos-gpdb-dev-5
